# Our Project Configuration

# -- Project & Founder --
cofounder_name: "Chris Davis"
product_name: "GrowthLogs"
elevator_pitch: "GrowthLogs helps growth practitioners track, manage, and learn from every experiment with ease, moving beyond messy spreadsheets to provide a centralized platform for clear hypotheses, real-time status updates, and actionable insights."

# -- Technical Stack --
language: typescript
framework: next.js
package_manager: npm
test_runner_command: "npm test"

# -- Workflow & VCS --
git_provider: github
main_branch: main

# -- Deployment --
deployment_target: netlify
